name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: echo "Deploying Linux-PERFORMANCE..."
